### ISSUE TITLE
[Suggestion] Inherit all Manual Loom Recipes

### ISSUE THREAD

**Issue by drhaber** [PyralIron/Advanced-TFC-Tech#3]
Instead of adding Craft Tweaker support this mod's loom should inherit the CT added recipes of the manual loom.

I imagine this would be a simpler method of _"adding"_ CT support without the hassle of adding all of the inetgrations and dependencies

**Comment by PyralIron** [comment]
Well I want to have the ability to make the ratios of input fiber amount to output cloth amount different between the power loom and manual loom. Also, not sure how you would configure power and time cost for the recipes, unless you just made it the same for every recipe. Plus, there needs to be a new Pirn item for each distinct recipe.

But, CT support at all would be nice, If you made a PR that does what you say + be able to keep the current power/time/cost values for the recipes then I would take a look at it.
