### ISSUE TITLE
Allow toogling compat. with mods this supports.

### ISSUE THREAD

**Issue by MagmaSlime123** [PyralIron/Advanced-TFC-Tech#7]
Title.

Allow toggling compat. with mods this mod supports.

**Comment by PyralIron** [comment]
What do you mean exactly?

**Comment by MagmaSlime123** [comment]
Add a config that lets you toggle compat with mods this supports.

**Comment by PyralIron** [comment]
Lol, you need to be more descriptive. What do you mean 'the mods this supports?' If you mean a toggle to disable the dependencies this mod requires, that's by definition not possible.

Or do you mean the compat with JEI and such?

**Comment by MagmaSlime123** [comment]
JEI compat and such, yes. Sorry.

**Comment by PyralIron** [comment]
Ah ok, but I still don't see the problem. Just tested it and this mod works perfectly fine without including JEI in your mods folder.

If it does crash for you please paste the crash report.
